apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-shop-tls
  namespace: sock-shop
spec:
  secretName: sock-shop-tls
  dnsNames:
  - www.techniche.com.ng
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment
  - server auth
