apiVersion: apps/v1
kind: Deployment
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sock-shop
  template:
    metadata:
      labels:
        app: sock-shop
    spec:
      containers:
      - name: sock-shop
        image: myrepo/sock-shop:latest
        ports:
        - containerPort: 80
