name: Sock-Shop Infrastructure CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
        
      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.15.0' # default is latest stable

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.12.0' # default is latest (stable)

      - name: Update kubeconfig for EKS Cluster
        run: |
          aws eks update-kubeconfig --name sock-shop --region eu-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2

      - name: Verify Kubernetes Connection
        run: kubectl get nodes

      - name: Setup Helm repos and update
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          kubectl apply -f ./sock-shop/ingress.yaml

      - name: Apply Kubernetes Manifests
        run: |
           kubectl apply -f ./sock-shop/
    

